apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: spring-boot-actuator-monitor
  name: spring-boot-actuator-monitor
spec:
  endpoints:
    - interval: 30s
      path: /actuator/prometheus
      port: web
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: java-service