{
 "title": "JAVA APP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, uri) \r\n         (rate(http_server_requests_seconds_bucket{uri=\"/user/{id}\"}[5m]))\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n      sum by (le, uri) \r\n         (rate(http_server_requests_seconds_bucket{uri=\"/user/{id}\"}[5m]))\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, uri) \r\n         (rate(http_server_requests_seconds_bucket{uri=\"/user/{id}\"}[5m]))\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - MAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(1, \r\n      sum by (le, uri) \r\n         (rate(http_server_requests_seconds_bucket{uri=\"/user/{id}\"}[5m]))\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}