{
 "title": "NGINX",
 "time": { "from": "2022-12-12T16:44:24.588Z", "to": "2022-12-12T16:51:51.722Z" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum ((rate(nginx_ingress_controller_nginx_process_requests_total[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum ((rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,  sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,  sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))*1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}